### ISSUE TITLE
Please explain plugin usefulness

### ISSUE THREAD

**Issue by pcav** [ivanbusthomi/cdf_converter#3]
In what is this different from: http://plugins.qgis.org/plugins/netcdfbrowser/ ?
Thanks.

**Comment by ivanbusthomi** [comment]
Hi @pcav,
The difference is that this plugin converts a specific variable and time slice in a NetCDF data to tiff. If I understand correctly, the NetCDF Browser plugin load data from specific variable and time slice. When I tried saving the loaded data into GeoTIFF, the result that I got still contains the other time slices while my original intention only extracting specific variable and time slice and saving it to a layer. If you know there is a way of doing it in NetCDF Browser, I would very glad if you can explain it to me.

**Comment by pcav** [comment]
Thanks. Could you please contact the author, to evaluate the opportunity of merging your work?
Sorry to bother, but we are trying hard to minimize the overlap between plugins, to reduce the confusion among users, and promote cooperation among plugin devs.
Also crayfish plugin may have useful functions.
Please do not hesitate asking if you need help.

**Comment by ivanbusthomi** [comment]
Hi @pcav 
I've checked Crayfish plugin, and apparently there is already a function to facilitate what I want to do. I will remove the upload request for CDFconverter then. 
Thank you very much for the suggestion.
